### ISSUE TITLE
Can't find variable: mainfile

### ISSUE THREAD

**Issue by AMAsskicker** [flyx/TeX.novaextension#10]
Was getting the error in issue #9 , updated latex packages, tex suite etc.   Now I get this error " The extension “TeX Suite” experienced an error. ReferenceError: Can't find variable: mainfile ". Can "build" latex file to make pdf just fine.  Error is produced when "run" is used.

**Comment by flyx** [comment]
Yeah I seriously should have tested that. uploaded fix.
