### ISSUE TITLE
Nova-TeX-Suite crashes with Nova 10.5

### ISSUE THREAD

**Issue by sstrecker** [flyx/TeX.novaextension#12]
Dear flyx: I have enjoyed using your Nova-TeX-Suite for quite some time now. Thanks for creating it and for making it publicly accessible. Please accept my apologies for asking your help: Having updated Nova to 10.5, Nova-TeX-Suite crashes upon loading any .tex document: "Extension Service Quit Unexpectedly". I would truly appreciate if you could find the time to look into this. Please let me know if I can be of further help in analysing the cause.

**Comment by flyx** [comment]
Thanks for the report, I'll look into it. Since I switched jobs I don't use LaTeX regularly anymore so this extension may suffer a bit from sparse maintenance, but I will do my best to react to reports, so writing issues is much appreciated.

**Comment by flyx** [comment]
Can't reproduce on macOS 13.0.1 aarch64 with Nova 10.5. There recently were some changes to Nova's `Process` API that may contribute to this, I can think of some adjustments that *might* help.

Could you try using [these modifications](https://flyx.org/files/TeX-Suite-snapshot.zip)? Just disable the stable extension version, open this one in a Nova window and then do Extensions -> Activate Project as Extension.

If this doesn't help, can you give me your macOS version and configuration values of the extension?

**Comment by sstrecker** [comment]
Thanks a million - your modifications work on my macOS 12.6.1, aarch64 with Nova 10.5.

**Comment by flyx** [comment]
I released a new version `1.0.4` that contains this fix.
