### ISSUE TITLE
Problem report: instantaneous crash of Nova 12.0b1 with Tex Suite active

### ISSUE THREAD

**Issue by ghost** [flyx/TeX.novaextension#13]
Reporting that I am getting reproducible instantaneous crashing of the 12.0b1 beta when I try to open existing Nova projects with the TeX Suite extension turned on. Not sure if this is Tex Suite's issue, I have reported this separately to Panic.

This is running on macOS 15.0.1 (24A348).

Please see the attached crash report.  This is right after launching Nova 12.0b1 and then opening an existing LaTeX document (.tex document) project.  

Steps to reproduce:

0.  Launch 11.10 and then Close any existing projects.  Current state should be no documents open.

1. Install 12.0b1 and restart Nova.

2.  Turn off all extensions.  Chief one to be turned off is:  TeX Suite.  TeX Suite is installed but not active (checkbox in the extension list is not checked.)

Comment:  you could do this step before installation of 12.0b1 but I did this after to see if 12.0b1 will load with the TeX Suite extension turned on, and it does.  Conclusion is that the crash that follows is not due to having the TeX suite running, it is due to having 12.0b1 try to execute stuff on a .tex document with the extension running.  Note also that the texlab language server is up and running.

3.  Load an existing project with .tex files, with previous state displaying a .tex file document as focus.

Result:  .tex and other documents open in the project are displayed, Nova seems to be working.  No edits were made in the demonstration here (see the attached crash report).

4.  Turn on TeX Suite extension by clicking its checkbox in the extensions list.

Result:  Immediate crash: document windows disappear, crash report window displayed.

I have attached the full crash report.

Hoping you can fix this one soon, for now I am back to Nova 11.9.

[crash report 11Oct24 655 pm Nova TeX Suite extension on.txt](https://github.com/user-attachments/files/17348416/crash.report.11Oct24.655.pm.Nova.TeX.Suite.extension.on.txt)

**Comment by flyx** [comment]
I'm gonna wait on Panic's response to this – please update this issue when they answer.

While the extension has some entitlements outside Nova's sandbox that could lead to a crash (access to file system, interaction with Skim), a crash right at startup strongly indicates that this is a Nova problem.

**Comment by ghost** [comment]
Resolved with 12.0b2 of Nova.
