### ISSUE TITLE
\partial interpreted as \part in folding (Confuses the outline view)

### ISSUE THREAD

**Issue by hhakula** [flyx/TeX.novaextension#8]
![Outline](https://user-images.githubusercontent.com/31202133/162448141-1c7771a9-8f19-402a-a2d6-2ec616303d1a.jpg)

Unfortunately my javascript skills are not sufficient to fix this (hopefully) simple issue. In more involved mathematics documents this becomes an issue.

**Comment by flyx** [comment]
There is a larger refactoring going on in branch `novalatex-merge`, overhauling this whole extension, which also fixes your error.

It is currently blocked by a Nova problem, see https://devforum.nova.app/t/nova-crashes-when-deactivating-my-extension/1468

I hope the next Nova release fixes this but I haven't heard from Panic yet. Once this is fixed, a new release is due soon.

**Comment by flyx** [comment]
This has just been fixed with release 1.0.0.
