### ISSUE TITLE
latexmk -task fails consistently / Current Latex File is OK

### ISSUE THREAD

**Issue by hhakula** [flyx/TeX.novaextension#9]
Here is the error message:
Could not run “latexmk”.
The extension assistant with identifier “org.flyx.tex::org.flyx.tex.latex.tasks” failed to resolve the action.

I have set the main file via the standard interface. Adding or removing latexmk options does not affect the behaviour.
If I use the Current Latex File -option, everything works just fine. I have projects with deep hierarchies and hence I'd love to see that option working again.

Nova is 9.2. I have a global latexmkrc. (This was the way I used the extension before the latest upgrade. I do appreciate your work!)

**Comment by flyx** [comment]
Can reproduce. Reason not immediately obvious.

The problem might be [this line](https://github.com/flyx/Nova-TeX-Suite/blob/5efdc40bb6ad9772f33694f509737a338ec10abe/TeX.novaextension/Scripts/main.js#L92) where the generated task contains a call to a registered command. This works for autogenerated tasks but might not for resolved tasks. The Nova docs are not very precise about this sadly.

I need to take this to the devforum. In the meantime, a workaround may be to have a local `latexmkrc` file that sets `@default_files`. This will autogenerate a task for every file given in there (files currently need to be given with `.tex` extension even though `latexmk` doesn't require this, WIP).

**Comment by flyx** [comment]
Submitted updated version which should fix this.
